### ISSUE TITLE
Cant pass params to albacore build task

### ISSUE THREAD

**Issue by jusefb** [Albacore/albacore#130]
I am trying to upgrade albacore to version 2, unfortunately it is not working.

I used to invoke the msbuild task and pass parameters to it in this way:

`Rake::Task["build_solution"].invoke(args[:solution_file], args[:build_cfg], log_dir, ['Rebuild'])`

which would call

`msbuild :build_solution, [:solution_file, :build_cfg, :log_dir, :build_options, :msbuild_path] do |msb, args| 
....
end`

I have changed 'msbuild' to the new 'build' task but now my args array is always null.

`build :build_solution, [:solution_file, :build_cfg, :log_dir, :build_options, :msbuild_path] do |msb, args| 
.......
end`

Any ideas?

**Comment by AMoghrabi** [comment]
Hey @haf I'm having the same problem as this issue but cannot figure out what you meant by your solution. I am trying to set up the `build` task with arguments:

    build :build_supporting, [:project_name] do |msb,args|
      ...
      ...

**Comment by haf** [comment]
I think you do `args[:project_name]`

**Comment by AMoghrabi** [comment]
Thanks for replying.

This is what I have:

Here is my `build` method definition according to your advice:

    build :build_supporting, [:project_name] do |msb,args|
      project_name = args[:project_name]
      ...
      ...
    end

Here is my method call:
`Rake::Task['build_supporting'].reenable`
`Rake::Task['build_supporting'].invoke(project_name)`

So because the special albacore `build` method is being treated as a rake task, I don't think I can call it as `build[myarg]`.

Am I incorrect or do you have any alternative solution?

**Comment by AMoghrabi** [comment]
Hey @haf 

Have you had a chance to review my last response? If it is not possible, I suppose I could use a "hack" by passing arguments through `ENV`. 

Thanks for your time.
